export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Dashboard } from './Dashboard';
export { default as Tools } from './Tools';
export { default as Inbox } from './Inbox';
export { default as History } from './History';
export { default as Insights } from './Insights';
export { default as NotFound } from './NotFound';
